In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel("Data-FakeRealCOVID.xlsx")
newDF = pd.read_csv("newDF.csv")

In [3]:
newDF = newDF.drop('Unnamed: 0',axis=1)

In [4]:
newDF

abia  abl  acc  acceler  access  accord  account  accur  achiev  \
0      0.0  0.0  0.0      0.0     0.0     0.0      0.0    0.0     0.0   
1      0.0  0.0  0.0      0.0     0.0     0.0      0.0    0.0     0.0   
2      0.0  0.0  0.0      0.0     0.0     0.0      0.0    0.0     0.0   
3      0.0  0.0  0.0      0.0     0.0     0.0      0.0    0.0     0.0   
4      0.0  0.0  0.0      0.0     0.0     0.0      0.0    0.0     0.0   
...    ...  ...  ...      ...     ...     ...      ...    ...     ...   
6415   0.0  0.0  0.0      0.0     0.0     0.0      0.0    0.0     0.0   
6416   0.0  0.0  0.0      0.0     0.0     0.0      0.0    0.0     0.0   
6417   0.0  0.0  0.0      0.0     0.0     0.0      0.0    0.0     0.0   
6418   0.0  0.0  0.0      0.0     0.0     0.0      0.0    0.0     0.0   
6419   0.0  0.0  0.0      0.0     0.0     0.0      0.0    0.0     0.0   

        acquir  ...  yesterday  yet  yobe  york  young  your  youtub  \
0     0.000000  ...        0.0  0.0   0.0   0.0    0.0   0.0     0.0   
1     0.000000  ...        0.0  0.0   0.0   0.0    0.0   0.0     0.0   
2     0.000000  ...        0.0  0.0   0.0   0.0    0.0   0.0     0.0   
3     0.000000  ...        0.0  0.0   0.0   0.0    0.0   0.0     0.0   
4     0.000000  ...        0.0  0.0   0.0   0.0    0.0   0.0     0.0   
...        ...  ...        ...  ...   ...   ...    ...   ...     ...   
6415  0.000000  ...        0.0  0.0   0.0   0.0    0.0   0.0     0.0   
6416  0.000000  ...        0.0  0.0   0.0   0.0    0.0   0.0     0.0   
6417  0.000000  ...        0.0  0.0   0.0   0.0    0.0   0.0     0.0   
6418  0.000000  ...        0.0  0.0   0.0   0.0    0.0   0.0     0.0   
6419  0.323644  ...        0.0  0.0   0.0   0.0    0.0   0.0     0.0   

       zealand  zero  zone  
0     0.000000   0.0   0.0  
1     0.000000   0.0   0.0  
2     0.000000   0.0   0.0  
3     0.000000   0.0   0.0  
4     0.000000   0.0   0.0  
...        ...   ...   ...  
6415  0.000000   0.0   0.0  
6416  0.000000   0.0   0.0  
6417  0.000000   0.0   0.0  
6418  0.000000   0.0   0.0  
6419  0.243707   0.0   0.0  

[6420 rows x 1381 columns]

In [5]:
data=torch.tensor(newDF.to_numpy())


In [6]:
data

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.2437, 0.0000, 0.0000]],
       dtype=torch.float64)

In [7]:
labels = []
for label in df.label.to_numpy():
  if label == 'real':
    labels.append(1)
  else:
    labels.append(0)
targets=torch.tensor(labels)
targets

tensor([1, 1, 0,  ..., 0, 0, 1])

In [8]:
targets.dtype

torch.int64

In [9]:
# Importer la fonction de splitting des données de scikit learn
from sklearn.model_selection import train_test_split


In [10]:
# Créer 4 tensors en résultat du splitting: données d'apprentissage, données de test, labels d'apprentissage, et labels de test  
atrain_data, test_data, atrain_targets, test_targets = train_test_split(data, targets, test_size=0.2)
atrain_data.shape

torch.Size([5136, 1381])

In [11]:
# Créer 4 tensors en résultat du splitting: données d'apprentissage, données de validation, labels d'apprentissage, et labels de validation  
train_data, validation_data, train_targets, validation_targets = train_test_split(atrain_data, atrain_targets, test_size=1000)
train_data.shape

torch.Size([4136, 1381])

In [12]:

# Afficher la taille de chaque tensor
print(train_data.shape, train_targets.shape)
print(validation_data.shape, validation_targets.shape)
print(test_data.shape,test_targets.shape)
print(train_data.shape[1])

torch.Size([4136, 1381]) torch.Size([4136])
torch.Size([1000, 1381]) torch.Size([1000])
torch.Size([1284, 1381]) torch.Size([1284])
1381


In [13]:
# Importer Dataset de torch.utils.data
from torch.utils.data import Dataset

In [14]:
# Créer une classe qui hérite de Dataset et redéfinit les méthodes 
class Covid_Dataset(Dataset):
    def __init__(self, data, targets):
        super(Covid_Dataset, self)
        self.data = data
        self.targets = targets
    def __getitem__(self, idx):
        return self.data[idx], self.targets[idx]
    def __len__(self):
        return len(self.targets)


In [15]:
# Créer les 3 objets en instantiant votre classe
train_dataset = Covid_Dataset(train_data, train_targets)
test_dataset = Covid_Dataset(test_data, test_targets)
validation_dataset = Covid_Dataset(validation_data, validation_targets)

In [16]:
# Importer DataLoader de torch.utils.data
from torch.utils.data import DataLoader

In [17]:
# Créer une variable pour la taille du batch
batch_size = 64

In [18]:
# Créer les objets DataLoader pour vos datasets d'apprentissage, test et validation en lui donner la taille du batch convenue

train_DL = DataLoader(train_dataset, batch_size=batch_size)
test_DL = DataLoader(test_dataset, batch_size=batch_size)
validation_DL = DataLoader(validation_dataset, batch_size=batch_size)


In [19]:
len(train_DL)

65

In [20]:
# Importer le module nn
import torch.nn as nn

In [21]:
# En utilisant Sequential(), créer un modèle avec l'architecture susmentionnée
CovidNN = nn.Sequential(nn.Linear(train_data.shape[1], 64),nn.ReLU(),nn.Linear(64, 32),nn.ReLU(),nn.Linear(32, 2))

In [22]:
# Définir la fonction du coût. On peut choisir CrossEntropyLoss
loss_function = nn.CrossEntropyLoss()

In [23]:
# Définir une fonction d'optimisation des coût: Adam par exemple. On devra définir un learning rate. On choisira 0.001.
import torch.optim as optim

optimizer = optim.Adam(CovidNN.parameters(), lr=0.001)

In [24]:
# Définir le nombre d'epochs. Commencer petit. 
nb_epochs = 10

In [25]:
for data,targets in train_DL:
  print(data)
  break

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], dtype=torch.float64)


In [26]:
# Créer une boucle sur les epochs:
for i in range(nb_epochs):
    # Spécifier qu'on est sur le mode entraînement
    CovidNN.train()
    # initialiser notre coût d'apprentissage à 0.0
    cout_appr = 0
    # Boucler sur les minibatchs des données d'entaînement (les données et leurs targets):
    for data,targets in train_DL:    
        # le vecteur des labels prédites par le modèle est le résultat de l'application du modèle sur le minibatch en cours. 
        output = CovidNN(data.float())
        # Calculer le coût en comparant les labels prédits aux targets du minibatch
        loss = loss_function(output,targets)
        # Backpropagation: 
        # Réinitialiser l'optimiseur
        optimizer.zero_grad()
        # Faire la backpropagation
        loss.backward()
        # Effectuer un pas d'optimisation
        optimizer.step()
        # Mettre à jour votre coût d'apprentissage en lui ajoutant le coût du data batch
        cout_appr += loss.item()
    # A la sortie de la boucle de l'entraînement, on calcule le coût moyen pour toutes les données training
    cout_moyen = cout_appr/len(train_dataset)
    # Initiliser le coût de validation à 0.0
    cout_valid = 0
    # Initialiser le nombre de prévisions correctes à 0
    prevision_correcte = 0
    # Spécifier qu'on est sur le mode d'évaluation
    CovidNN.eval()
    # Indiquer à Pytorch qu'on ne va pas faire de Gradient descent (comme on est dans l'évaluation)
    with torch.no_grad():
        # Boucler sur les minibatchs des données de validation (les données et leurs targets):
        for data,targets in validation_DL:  
            # le vecteur des labels prédites par le modèle est le résultat de l'application du modèle sur le minibatch en cours. 
            output = CovidNN(data.float())
            # Calculer le coût en comparant les labels prédits aux targets du minibatch
            loss = loss_function(output,targets)
            # Mettre à jour votre coût de validation en lui ajoutant le coût du data batch
            cout_valid += loss.item()
            # Mettre à jour le nombre de prévision correctes en y ajoutant le nombre des bonnes prévision sur ce batch
            # On y compare le label prédit avec le labels du minibatch. 
            # Penser à utiliser argmax pour avoir la prévision finale à partir du vecteur de prévision
            #prevision_correcte += len(output[output == targets])
            prevision_correcte += torch.sum((torch.argmax(output, dim=1) == targets)).item()
        # A la sortie de cette boucle, calculer le coût moyen de validation
        cout_valid_moyenne = cout_valid/len(validation_dataset)
        
        # Calculer la précision: la moyenne des prévisions correctes sur l'ensemble des observations dans le dataset validation 
        prevision_correcte_moyenne = prevision_correcte/len(validation_dataset)

    # Afficher pour chaque itération le coût d'entraînement, le coût de validation, et la précision.
    
        

In [27]:
prevision_correcte_moyenne

0.908

In [28]:
# Initiliser le coût de test à 0.0
cout_loss = 0
# Initialiser le nombre de prévisions correctes à 0
prevision_correcte = 0
with torch.no_grad():
    # Boucler sur les minibatchs des données de test (les données et leurs targets):
    for data,targets in test_DL:  
        # le vecteur des labels prédites par le modèle est le résultat de l'application du modèle sur le minibatch en cours. 
        output = CovidNN(data.float())
        # Calculer le coût en comparant les labels prédits aux targets du minibatch
        loss = loss_function(output,targets)
        # Mettre à jour votre coût de test en lui ajoutant le coût du data batch
        cout_valid += loss.item()
        # Mettre à jour le nombre de prévision correctes en y ajoutant le nombre des bonnes prévision sur ce batch
        # On y compare le label prédit avec le labels du minibatch. 
        # Penser à utiliser argmax pour avoir la prévision finale à partir du vecteur de prévision
        #prevision_correcte += len(output[output == targets])
        prevision_correcte += torch.sum((torch.argmax(output, dim=1) == targets)).item()
    # A la sortie de cette boucle, calculer le coût moyen de test
    cout_valid_moyenne = cout_valid/len(test_dataset)

    # Calculer la précision: la moyenne des prévisions correctes sur l'ensemble des observations dans le dataset test 
    prevision_correcte_moyenne = prevision_correcte/len(test_dataset)

In [29]:
prevision_correcte_moyenne

0.897196261682243

In [30]:
# sauvegarder le modèle dans un fichier pickle
torch.save(CovidNN,'CovidNN.pr')